name: Deploy NGINX to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone us-central1-c --project ${{ secrets.GCP_PROJECT }}

    - name: Deploy to GKE
      run: 
      


      |
        kubectl apply -f k8s/nginx.yaml
        kubectl rollout status deployment/nginx-deployment
