name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: List files
        run: ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Java-Project/requirements.txt   # 👈 Change path if needed

      - name: Lint code with flake8
        run: flake8 .

      - name: Bandit Security Scan
        run: bandit -r .

      - name: Unit testing and coverage
        run: pytest --maxfail=1 --disable-warnings -q
