name: Secret Detection

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks to detect secrets
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks-report.sarif
